################### MARIADB PLAYBOOK ###############

    - name: Install Maria DB from OS repo
      yum:
        name: mariadb-server
        state: latest

    - name: Enable Maria DB service
      service:
        name: mariadb
        status: enabled

    - name: Start Maria DB service
      service:
        name: mariadb
        status: restarted 
    
