################### MARIADB PLAYBOOK ###############

    - name: Install Maria DB from OS repo
      yum:
        name: mariadb-server
        state: latest
      become: true

    - name: Enable Maria DB service
      service:
        name: mariadb
        status: enabled
      become: true

    - name: Start Maria DB service
      service:
        name: mariadb
        status: restarted
      become: true
    
